name = "elite-voucher-api"
main = "src/index.js"
compatibility_date = "2024-06-05"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
ENVIRONMENT = "production"
APP_DOMAIN = "https://vcelite.pages.dev"
GOOGLE_REDIRECT_URI = "https://vcelite.pages.dev/auth/callback"
LOCAL_LOGIN_ID = "admin"
LOCAL_LOGIN_ROLE = "super_admin"

[[d1_databases]]
binding = "DB"
database_name = "elite-voucher"
database_id = "9d3f6d61-956c-4f86-849b-91c12efffd28"

[[kv_namespaces]]
binding = "KV_SESSIONS"
id = "272900c235dd401abf9413638fc0e504"

[[kv_namespaces]]
binding = "KV_SETTINGS"
id = "4bcaacd9dc3f47da8e35741dde84f464"

[[kv_namespaces]]
binding = "KV_PUBLIC_CACHE"
id = "4cb1cdca7ccd46fdbbd96c3228ba1234"
